DROP DATABASE IF EXISTS SBCC;
CREATE DATABASE SBCC;
USE SBCC;
CREATE TABLE player(
   playerId VARCHAR(15) NOT NULL PRIMARY KEY 
  ,playerName   VARCHAR(30) NOT NULL
  ,matchesPlayed INTEGER  NOT NULL
  ,runScored INTEGER  NOT NULL
  ,playingZone VARCHAR(15) NOT NULL
  ,playerType  VARCHAR(15)  NOT NULL
  ,starRating  DOUBLE(5,2)  NOT NULL
);